/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_pedestrian_jni_MainActivity */

#ifndef _Included_com_example_pedestrian_jni_MainActivity
#define _Included_com_example_pedestrian_jni_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_pedestrian_jni_MainActivity
 * Method:    Add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_pedestrian_jni_MainActivity_Add
  (JNIEnv *, jobject, jint a, jint b){
  	return a + b;
  }

#ifdef __cplusplus
}
#endif
#endif